name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: https://github.com/Egorich42/coordinate_calculator.git
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Set up Docker Compose
      uses: docker/setup-compose-action@v1

    - name: Create .env file from GitHub Secrets
      run: |
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
        echo "APP_PORT=${{ secrets.APP_PORT }}" >> .env

    - name: Build the Docker images
      run: docker-compose build

    - name: Run tests
      run: docker-compose run tests

    - name: Shutdown
      run: docker-compose down

